affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ''
image:
  pullPolicy: Always
  repository: junshen1969/automate-openshift-deployment
  tag: 9803b213-4a4b-4c0c-92e7-c806edea830d
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
initialDelaySeconds: 5
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 3000
  type: NodePort
serviceAccount:
  annotations: {}
  create: false
  name: ''
tolerations: []
